In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [11]:
data = pd.read_csv('merged_data')
data['支付时间'] = pd.to_datetime(data['支付时间'], errors='coerce', format='%Y/%m/%d %H:%M')

In [16]:
data['Year'] = data['支付时间'].dt.year.astype('Int64')
data['Month'] = data['支付时间'].dt.month.astype('Int64')
data['Day'] = data['支付时间'].dt.day.astype('Int64')

In [17]:
data.sample(10)

,订单号,设备ID,应付金额,实际金额,商品,支付时间,地点,状态,提现,大类,二级类,Year,Month,Day
2232,DD20170602175335816D381DF3964,E43A6E078A04228,4.0,4.0,营养快线,2017-01-09 17:48:00,C,已出货未退款,已提现,饮料,乳制品,2017,1,9
20993,DD2017072108121278185A04573BF,E43A6E078A04228,4.0,4.0,阿萨姆奶茶,2017-11-14 15:33:00,C,已出货未退款,已提现,饮料,茶饮料,2017,11,14
52823,DD2017061603021594590312466B8,E43A6E078A04228,3.0,3.0,统一绿茶,2017-12-26 12:23:00,C,已出货未退款,已提现,饮料,茶饮料,2017,12,26
30755,DD201708167493601723583617387,E43A6E078A04172,4.5,4.5,250ml燕塘红枣牛奶,2017-10-25 11:54:00,A,已出货未退款,已提现,饮料,乳制品,2017,10,25
41330,DD20170419124421754C8A49C40A1,E43A6E078A04134,4.0,4.0,脉动,2017-12-29 15:51:00,B,已出货未退款,已提现,饮料,功能饮料,2017,12,29
29988,DD201708167493905106955763392,E43A6E078A04228,1.5,1.5,12g劲仔小鱼麻辣味,2017-08-12 11:11:00,C,已出货未退款,已提现,非饮料,肉干/豆制品/蛋,2017,8,12
5797,DD20170729110354246AE02BD3E35,E43A6E078A04134,1.5,1.5,鸭翅,2017-10-03 17:30:00,B,已出货未退款,已提现,非饮料,肉干/豆制品/蛋,2017,10,3
32507,DD201708230044181714A2705DDEA,E43A6E078A04228,3.0,3.0,怡宝纯净水,2017-08-14 09:18:00,C,已出货未退款,已提现,饮料,水,2017,8,14
64215,DD201708232032491192D7B1603B7,E43A6E078A04228,3.5,3.5,雪碧330ml,2017-12-18 20:58:00,C,已出货未退款,已提现,饮料,碳酸饮料,2017,12,18
15405,DD20170709145921729127C88A298,E43A6E078A06874,3.5,3.5,可口可乐最新款,2017-09-02 15:22:00,E,已出货未退款,已提现,饮料,碳酸饮料,2017,9,2

In [22]:
grouped_data = data.groupby(['Year','Month', '设备ID']).agg(
    total_amount=('实际金额', 'sum'),
    total_orders=('订单号', 'count'),
    unique_days=('支付时间', lambda x: x.dt.date.nunique())
).reset_index()

In [23]:
grouped_data.head(5)

   Year  Month             设备ID  total_amount  total_orders  unique_days
0  2017      1  E43A6E078A04134        1373.6           366           23
1  2017      1  E43A6E078A04172        1509.7           335           25
2  2017      1  E43A6E078A04228        1640.5           379           26
3  2017      1  E43A6E078A06874        1656.8           354           27
4  2017      1  E43A6E078A07631         956.4           259           23

In [24]:
grouped_data['average_transaction_amount_per_order'] = grouped_data['total_amount'] / grouped_data['total_orders']
grouped_data['average_daily_order_count'] = grouped_data['total_orders'] / grouped_data['unique_days']

In [26]:
grouped_data

,Year,Month,设备ID,total_amount,total_orders,unique_days,average_transaction_amount_per_order,average_daily_order_count
0,2017,1,E43A6E078A04134,1373.6,366,23,3.753005,15.913043
1,2017,1,E43A6E078A04172,1509.7,335,25,4.506567,13.400000
2,2017,1,E43A6E078A04228,1640.5,379,26,4.328496,14.576923
3,2017,1,E43A6E078A06874,1656.8,354,27,4.680226,13.111111
4,2017,1,E43A6E078A07631,956.4,259,23,3.692664,11.260870
5,2017,2,E43A6E078A04134,602.3,185,24,3.255676,7.708333
6,2017,2,E43A6E078A04172,440.5,114,25,3.864035,4.560000
7,2017,2,E43A6E078A04228,792.0,207,26,3.826087,7.961538
8,2017,2,E43A6E078A06874,938.7,258,26,3.638372,9.923077
9,2017,2,E43A6E078A07631,435.5,141,24,3.088652,5.875000
10,2017,3,E43A6E078A04134,957.9,265,6,3.614717,44.166667
11,2017,3,E43A6E078A04172,914.3,255,5,3.585490,51.000000
12,2017,3,E43A6E078A04228,991.5,263,5,3.769962,52.600000
13,2017,3,E43A6E078A06874,1507.0,350,7,4.305714,50.000000
14,2017,3,E43A6E078A07631,826.7,192,4,4.305729,48.000000
15,2017,4,E43A6E078A04134,2457.4,603,30,4.075290,20.100000
16,2017,4,E43A6E078A04172,1804.5,447,30,4.036913,14.900000
17,2017,4,E43A6E078A04228,3232.3,734,30,4.403678,24.466667
18,2017,4,E43A6E078A06874,3723.1,895,30,4.159888,29.833333
19,2017,4,E43A6E078A07631,1679.1,443,30,3.790293,14.766667
20,2017,5,E43A6E078A04134,3681.2,869,30,4.236133,28.966667
21,2017,5,E43A6E078A04172,3385.1,756,30,4.477646,25.200000
22,2017,5,E43A6E078A04228,3729.4,789,30,4.726743,26.300000
23,2017,5,E43A6E078A06874,5699.0,1292,30,4.410991,43.066667
24,2017,5,E43A6E078A07631,2392.1,564,30,4.241312,18.800000
25,2017,6,E43A6E078A04134,7550.3,1856,30,4.068050,61.866667
26,2017,6,E43A6E078A04172,6755.1,1669,30,4.047394,55.633333
27,2017,6,E43A6E078A04228,8472.2,1882,30,4.501700,62.733333
28,2017,6,E43A6E078A06874,9899.7,2593,30,3.817856,86.433333
29,2017,6,E43A6E078A07631,4187.0,1040,30,4.025962,34.666667
30,2017,7,E43A6E078A04134,1518.6,345,29,4.401739,11.896552
31,2017,7,E43A6E078A04172,1950.5,476,27,4.097689,17.629630
32,2017,7,E43A6E078A04228,3047.1,764,29,3.988351,26.344828
33,2017,7,E43A6E078A06874,3186.4,813,30,3.919311,27.100000
34,2017,7,E43A6E078A07631,1340.8,317,27,4.229653,11.740741
35,2017,8,E43A6E078A04134,3516.1,981,31,3.584200,31.645161
36,2017,8,E43A6E078A04172,2236.9,666,31,3.358709,21.483871
37,2017,8,E43A6E078A04228,4927.2,1259,31,3.913582,40.612903
38,2017,8,E43A6E078A06874,6722.5,1767,31,3.804471,57.000000
39,2017,8,E43A6E078A07631,2371.3,715,31,3.316503,23.064516
40,2017,9,E43A6E078A04134,7207.3,1745,30,4.130258,58.166667
41,2017,9,E43A6E078A04172,4479.5,1040,30,4.307212,34.666667
42,2017,9,E43A6E078A04228,7429.0,1678,30,4.427294,55.933333
43,2017,9,E43A6E078A06874,17054.3,4134,30,4.125375,137.800000
44,2017,9,E43A6E078A07631,3833.1,983,30,3.899390,32.766667
45,2017,10,E43A6E078A04134,8331.6,2026,31,4.112340,65.354839
46,2017,10,E43A6E078A04172,6292.4,1565,31,4.020703,50.483871
47,2017,10,E43A6E078A04228,9469.7,2216,31,4.273330,71.483871
48,2017,10,E43A6E078A06874,10208.6,2777,31,3.676125,89.580645
49,2017,10,E43A6E078A07631,4606.7,1186,31,3.884233,38.258065
50,2017,11,E43A6E078A04134,8669.9,2031,29,4.268784,70.034483
51,2017,11,E43A6E078A04172,5187.0,1160,30,4.471552,38.666667
52,2017,11,E43A6E078A04228,8456.7,1943,30,4.352393,64.766667
53,2017,11,E43A6E078A06874,21501.8,5020,30,4.283227,167.333333
54,2017,11,E43A6E078A07631,4673.4,1210,30,3.862314,40.333333
55,2017,12,E43A6E078A04134,8104.1,2210,31,3.667014,71.290323
56,2017,12,E43A6E078A04172,7587.1,2003,31,3.787868,64.612903
57,2017,12,E43A6E078A04228,9380.5,2379,31,3.943043,76.741935
58,2017,12,E43A6E078A06874,13557.5,3252,31,4.168973,104.903226
59,2017,12,E43A6E078A07631,5941.2,1663,31,3.572580,53.645161